name: deal_o_round
description: Flutter port of the originally PlayN based Deal-O-Round game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.25+25

environment:
  sdk: ">=3.10.4"
  flutter: ">=3.38.5"

dependencies:
  collection: ^1.19.1
  flutter_soloud: ^2.0.0
  games_services: ^5.0.0
  get: ^4.7.3
  intl: ^0.20.2
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.13
  shared_preferences: ^2.5.4
  spinner_input_plus: ^0.0.4
  universal_platform: ^1.1.0
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^9.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cards
      fonts:
        - asset: fonts/cards.ttf
    - family: Musicals
      fonts:
        - asset: fonts/musicals.ttf
    - family: Roboto-Condensed
      fonts:
        - asset: fonts/roboto-condensed.ttf
    - family: Stint-Ultra-Condensed
      fonts:
        - asset: fonts/stint-ultra-condensed.ttf
