name: deal_o_round
description: Flutter port of the originally PlayN based Deal-O-Round game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.25+25

environment:
  sdk: ">=3.8.1"
  flutter: ">=3.32.4"

dependencies:
  assets_audio_player: ^3.1.1
  audioplayers: ^6.5.1
  collection: ^1.19.1
  games_services: ^4.1.1
  get: ^4.7.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  spinner_input_plus: ^0.0.4
  universal_platform: ^1.1.0
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^8.4.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cards
      fonts:
        - asset: fonts/cards.ttf
    - family: Musicals
      fonts:
        - asset: fonts/musicals.ttf
    - family: Roboto-Condensed
      fonts:
        - asset: fonts/roboto-condensed.ttf
    - family: Stint-Ultra-Condensed
      fonts:
        - asset: fonts/stint-ultra-condensed.ttf
